### ISSUE TITLE
output message for marker/sample missingness indicates the opposite of what's calculated

### ISSUE THREAD

**Issue by jgrundstad** [lemieuxl/pyGenClean#24]
Considering the documentation for the Sample and Marker Missingness modules (e.g. _The missingness threshold (remove samples with more than x percent missing genotypes). [Default: 0.100]_), the logged results appear to indicatethe opposite:

`Number of samples with missing rate less or equal to 0.1     5     -5`*
- in this case, "5" samples represents less than 0.7% of my cohort, which would appear accurate if these samples had missing rates _more than or equal to 0.1_.

Am I understanding this correctly?  Thanks!

**Comment by lemieuxl** [comment]
The output message is indeed wrong. The text in the result description is correct, but the information in the summary results table should read:

```
Number of samples with missing rate higher than 0.1    5        -5
```

This represents the number of samples that were excluded from the dataset.
